version: "3.7"

services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
       MYSQL_ROOT_PASSWORD: P123456
       MYSQL_DATABASE: bookstore_db
       MYSQL_USER: clarusway
       MYSQL_PASSWORD: Clarusway_1
    networks:
      - haleynet

  myapp:
    image: fhalearslan/bookstoreapi:1.0
    container_name: myapp
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - haleynet

  networks:
    haleynet:    
